### ISSUE TITLE
Selection of `NULL` values does not work

### ISSUE THREAD

**Issue by spren9er** [uwdata/mosaic#145]
When clicking on a bar representing the total amount of records where a specific column is `NULL`, filtering does not work.

Example:

```yaml
data:
  penguins: { file: data/penguins.csv }
params:
  query: { select: crossfilter }
vconcat:
- name: total
  plot:
  - mark: barX
    data: { from: penguins, filterBy: $query }
    x: { count: '' }
  xLabel: Total →
  xDomain: Fixed
- vspace: 20
- name: sex
  plot:
  - mark: barY
    data: { from: penguins, filterBy: $query }
    x: sex
    y: { count: '' }
  - select: toggleX
    as: $query
  xLabel: ''
  yLabel: Total
  xDomain: Fixed
  yDomain: Fixed
```

![Bildschirmfoto 2023-08-03 um 09 09 10](https://github.com/uwdata/mosaic/assets/5602551/47aeedf2-8cd9-42b9-ba1b-b83f8e2b804f)

In above example, clicking on the right bar of lower bar chart shows a total of `0` in upper bar chart.

This bug was first mentioned in #144. Note from @jheer:

> ..., the issue with the NULL is a bug, due to the toggle interactors generating equality (=) comparisons rather than IS NOT DISTINCT FROM (which is null safe).
