### ISSUE TITLE
Highlight interactor does not work properly with data cube indexing

### ISSUE THREAD

**Issue by spren9er** [uwdata/mosaic#159]
I have a simple _vgplot_ specification with cross filter selection and two bar charts.
Bars should be highlighted when selected.

```yaml
data:
  athletes: { file: data/athletes.csv }
params:
  query: { select: crossfilter }
  selectNationality: { select: single }
  selectSport: { select: single }
vconcat:
  - plot:
    - mark: barX
      data: { from: athletes, filterBy: $query }
      x: { count: }
      y: nationality
      order: nationality
      sort: {
        y: '-x',
        limit: 10
      }
    - select: highlight
      by: $selectNationality
    - select: toggleY
      as: $selectNationality
    - select: toggleY
      as: $query
      width: 600
      height: 400
    marginLeft: 80
  - vspace: 10
  - plot:
    - mark: barX
      data: { from: athletes, filterBy: $query }
      x: { count: }
      y: sport
      order: sport
      sort: {
        y: '-x',
        limit: 10
      }
    - select: highlight
      by: $selectSport
    - select: toggleY
      as: $selectSport
    - select: toggleY
      as: $query
      width: 600
      height: 400
    marginLeft: 80
```

Highlighting doesn't work like expected.
There'll be bars, which aren't highlighted anymore at a certain point (mark indexes from `__data__` seem to get out of sync) or bars, where highlighting appears on other bars.

Reproducible examples for above specification:

- Clicking `USA` on upper chart, and then clicking one of the first three bars on lower chart, bar `USA` will lose highlighting.
- Clicking `athletics` on lower chart, and then clicking on `USA`, `POL` or `UKR` on upper chart, won't highlight country.

I tried different settings (with and without `order` attribute), but that didn't help.

When disabling cube indexing in coordinator (`indexes = false`), highlighting works properly.
