### ISSUE TITLE
MosaicWidget not displaying in Jupyter...

### ISSUE THREAD

**Issue by jgunstone** [uwdata/mosaic#608]
to reproduce:

with `environment.yml`

```yml
name: mosaic-test
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
# ---------------------------------
# dev env currently contains
# requirements for both UI and API
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - jupyterlab
  - frictionless
  - pandas
  - numpy
  - duckdb
  - anywidget
  - ipywidgets
  - pip>=24.2
  - pip:
      - mosaic-widget
```

create env and launch jupyter
```shell
mamba env create -f environment.yml
jupyter lab
```

in jupyter 
```py
import pandas as pd
import yaml
import requests
from mosaic_widget import MosaicWidget

url = "https://raw.githubusercontent.com/uwdata/mosaic/main/specs/yaml/weather.yaml"
r = requests.get(url)
spec = yaml.safe_load(r.content)
weather = pd.read_csv("https://uwdata.github.io/mosaic-datasets/data/seattle-weather.csv", parse_dates=['date'])
mw = MosaicWidget(spec, data = {"weather": weather})
mw
```

![image](https://github.com/user-attachments/assets/4d517686-11e1-4c46-916f-c83973da20f2)
