### ISSUE TITLE
vgplot Mark TipOptions format - possibly incorrect parsing.

### ISSUE THREAD

**Issue by venkat-oss** [uwdata/mosaic#709]
I have a mosaic vgplot yaml specification that looks like this:

```
plot:
- mark: lineY
  data: { from: tabular_data }
  x: TimeMinutes
  y: Value
  stroke: MetricName
  tip: {format: {x: true, y: true, stroke: true, z: false }}
width: 900
height: 580
```

Expected behavior of the plot tip with format option:
`MetricName system.cpu.load_average.1m {color}`

Observed behavior of the plot tip with format option:
`stroke system.cpu.load_average.1m {color}`

Image for reference:
![Image](https://github.com/user-attachments/assets/aa752a19-7e82-40d1-90bd-9ab8c424d377)

Is this expected or am I providing an incorrect chart specification? Thank you for the great work on this!!
